import { GamingRig, ParsecPreset } from '../types';

export function getParsecUri(rig: GamingRig): string {
  if (rig.parsecPeerId) {
    const cleanId = rig.parsecPeerId.trim();
    // Parsec supports direct peer connections via URI
    return `parsec://peer_id=${encodeURIComponent(cleanId)}`;
  }
  if (rig.parsecShareLink && rig.parsecShareLink.startsWith('parsec://')) {
    return rig.parsecShareLink;
  }
  return 'parsec://';
}

export function getParsecWebUrl(rig: GamingRig): string {
  if (rig.parsecShareLink && rig.parsecShareLink.startsWith('http')) {
    return rig.parsecShareLink;
  }
  return 'https://web.parsec.app/';
}

export function launchParsecSession(rig: GamingRig): { uri: string; webUrl: string } {
  const uri = getParsecUri(rig);
  const webUrl = getParsecWebUrl(rig);
  
  try {
    // Try opening parsec:// URI directly
    window.location.href = uri;
  } catch (err) {
    console.warn('Direct URI launch failed, fallback to web link:', err);
  }

  return { uri, webUrl };
}

export function generateParsecConfig(preset: ParsecPreset): string {
  const res = preset.resolution === 'custom' ? (preset.customResolution || '1920x1080') : preset.resolution;
  const [width, height] = res.split('x');

  return `# Parsec Optimized Gaming Config (config.txt)
# Generated by ParsecWake Mobile Suite
client_vsync = 0
encoder_bitrate = ${preset.bitrateMbps}
encoder_fps = ${preset.fps}
encoder_h265 = ${preset.decoder === 'H.265' || preset.decoder === 'AV1' ? 1 : 0}
client_decoder_h265 = ${preset.decoder === 'H.265' || preset.decoder === 'AV1' ? 1 : 0}
client_window_width = ${width || '1920'}
client_window_height = ${height || '1080'}
client_audio_quality = ${preset.audioQuality === 'High' ? 1 : 0}
encoder_color_format = ${preset.colorFormat === '4:4:4' ? 1 : 0}
client_immersive = 1
`;
}

export function generateVirtualDisplayScript(rigName: string): string {
  return `# PowerShell Script: Setup Parsec Virtual Display & Keep Active
# Run on ${rigName} as Administrator
Write-Host "Configuring Virtual Display for Headless Parsec Gaming..." -ForegroundColor Cyan

# Check if Parsec Virtual Display Driver is enabled in Parsec config
$parsecConfigPath = "$env:APPDATA\\Parsec\\config.txt"
if (Test-Path $parsecConfigPath) {
    Add-Content -Path $parsecConfigPath -Value "\nhost_virtual_monitors = 1"
    Write-Host "[+] Enabled host_virtual_monitors in Parsec config" -ForegroundColor Green
}

# Ensure Windows doesn't lock or sleep HDMI output
powercfg -change -standby-timeout-ac 0
powercfg -change -monitor-timeout-ac 0
Write-Host "[+] Power timeouts set to Never (24/7 Gaming Ready)" -ForegroundColor Green

Write-Host "Parsec Headless Host Ready! You can now turn off your physical monitor." -ForegroundColor Green
`;
}

export function generateAutoLoginGuide(): string {
  return `# Windows Auto-Login Setup (For Headless Remote Wake)
1. Press Win + R, type 'netplwiz', and press Enter.
2. Uncheck "Users must enter a user name and password to use this computer".
3. Click Apply, enter your Windows password twice, and click OK.
4. If the checkbox is missing on Windows 11:
   - Run in PowerShell (Admin):
   reg add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\PasswordLess\\Device" /v DevicePasswordLessBuildVersion /t REG_DWORD /d 0 /f
   - Reopen 'netplwiz' and uncheck the box.
`;
}
